apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-stats
  labels:
    app: sys-stats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sys-stats
  template:
    metadata:
      labels:
        app: sys-stats
    spec:
      containers:
      - name: sys-stats
        image: public.ecr.aws/x4u2j5r7/stats:latest
        ports:
        - containerPort: 80 
      - name: api
        image: public.ecr.aws/x4u2j5r7/red-acre/api:latest
        ports:
        - containerPort: 5000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sys-stats
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: v1
kind: Service
metadata:
  name: sys-stats
spec:
  selector:
    app: sys-stats
  type: LoadBalancer  
  ports:
    - name: sys-stats
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api
      protocol: TCP
      port: 5000      
      

